# Generated by Django 6.0.6 on 2026-06-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField()),
                ('Department', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('Doctor', models.CharField(max_length=50)),
                ('Msg', models.CharField(max_length=200)),
            ],
        ),
    ]
