# Generated by Django 6.0.6 on 2026-06-17 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='appointments',
            old_name='Department',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='appointments',
            old_name='Doctor',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='appointments',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='appointments',
            old_name='Msg',
            new_name='msg',
        ),
        migrations.RenameField(
            model_name='appointments',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='appointments',
            old_name='Phone',
            new_name='phone',
        ),
    ]
