# Generated by Django 6.0.6 on 2026-06-17 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicapp', '0002_rename_date_appointments_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='msg',
            new_name='message',
        ),
    ]
