# Generated by Django 6.0.6 on 2026-06-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicapp', '0003_rename_msg_appointments_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
